### ISSUE TITLE
Freeway sometimes returning wrong content type

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/freeway#19]
From: https://discord.com/channels/806902334369824788/864892166470893588/1039784724413022230

https://bafybeie27f5vgj6m75htnf3mdkdaxagsibygyepnkiauxlge35u7vkeini.ipfs.w3s.link/profile/svg.svg returns the wrong content type because of Freeway

![image](https://user-images.githubusercontent.com/11778450/200885071-4c901ba9-3d32-4922-98d6-61b38f297cfc.png)
vs.
![image](https://user-images.githubusercontent.com/11778450/200885092-3b4088e6-ccf7-462c-8909-f9359cf269d1.png)

Reason why it's an issue: "When using this in an <img/> tag Chrome Cross-Origin Read Blocks (CORB) the content and gives me an empty file because it doesn't allow application/xml as an image: https://www.chromium.org/Home/chromium-security/corb-for-developers/."

From @vasco-santos: "I know we are using some libs to get the mime types, so we need to debug there and see. it might be a bug in one of the libs we use to infer this, so might take some time"

**Comment by olizilla** [comment]
our content-type magic needs more magic
https://github.com/web3-storage/gateway-lib/blob/a61113ee27d7b0488a0a9e3df59bd37a1ff4bcad/src/util/mime.js#L23-L38
