### ISSUE TITLE
Paths with `#` not handled as expected

### ISSUE THREAD

**Issue by rvagg** [web3-storage/freeway#83]
This one might be a bit subtle, and perhaps there's room for some discussion here but here's a discrepancy between how Lassie thinks of a traversal vs how freeway does.

Consider the CID+path currently with the most errors recorded for our "extraneous blocks in CAR" error coming out of freeway: `bafybeifcomhxkhspd6imbfl726cfzfrfk6ooma5gvr6vdohmo3aa5biscm/#13 Orias`.

It looks like a name anchor in a URL, but it's been provided to us as a path and we're interpreting it as such. Likely there's an error somewhere up the chain, perhaps all the way to the browser, or maybe in the encoded page the user is navigating from and through the gateway, but that's a separate issue.

`lassie fetch 'bafybeifcomhxkhspd6imbfl726cfzfrfk6ooma5gvr6vdohmo3aa5biscm/#13 Orias'` will yield just a single block, because it wants to use that block to find the next segment, `#13 Orias`, but one doesn't exist, because the referenced CID is a sharded file. So all you get back is a single block, no more, and it's technically an error for the user because their query couldn't be fulfilled (currently debating exactly what to do with unfulfillable paths [here](https://github.com/filecoin-project/lassie/pull/386) but that's a separate issue again).

But freeway deals with this differently:

```
curl -v -H 'Accept: application/vnd.ipld.car;version=1;order=dfs;dups
=y' 'https://dag.w3s.link:443/ipfs/bafybeifcomhxkhspd6imbfl726cfzfrfk6ooma5gvr6vdohmo3aa5biscm/%2313%20Orias?dag-scope=entity' -o bafybeifcomhxkhspd6imbfl726cfzfrfk6ooma5gvr6vdohmo3aa5biscm_w3s.car
```

yields a CAR with 21 blocks that I think form a full sharded file. So I guess freeway is either stripping off the `#` at some point, or doing a best-guess select-all when it gets to a terminal rather than attempting to go further and failing early with the single block that doesn't provide a path to the next path segment.

Error logs through Rhea have a ton of these, but most of them seem to have email addresses in them so I'll refrain from pasting in here.

**Comment by alanshaw** [comment]
Hopefully fixed by https://github.com/web3-storage/dag.w3s.link/commit/e3c9a3146ed6d72e17f719426be32c459b4291f8 🤞

**Comment by alanshaw** [comment]
For:

```console
$ curl -v -H 'Accept: application/vnd.ipld.car;version=1;order=dfs;dups=y' 'https://dag.w3s.link:443/ipfs/bafybeifcomhxkhspd6imbfl726cfzfrfk6ooma5gvr6vdohmo3aa5biscm/%2313%20Orias?dag-scope=entity' -o w3s.car
```

We now get:

```
bafybeifcomhxkhspd6imbfl726cfzfrfk6ooma5gvr6vdohmo3aa5biscm
├── bafkreiftfr6ujp4u5grlwpi55lto4v2b44k7z75vna6fg3g3jvgzsf6voy (missing)
├── bafkreifvq4wivy2o36wsttpgqvxnefthmvboxifqvsa5osu5jv2siafsyi (missing)
├── bafkreigxluptb6wf3767pycqxiwyfvej3lbpghvmgvn3rl3dt7vtjxvoj4 (missing)
├── bafkreie4egeyhltp55gktyml5xte4uztdqquwslnyc3cjssk7zbhtx7ku4 (missing)
├── bafkreibjkt6a5sckqtjs5nswq6g4dqkftm63mh7up5wchjymlonmqodtiq (missing)
├── bafkreibbhmfzpsaaudwcc56njsgrzjxf5q47nr6uz5iqgnhikzoikhcqxq (missing)
├── bafkreiexp3vdaitcazqbh7syqtb7un6f2pr42m76upthrkc4ju6di2updm (missing)
├── bafkreigz2nmbuxtqmtgfbrpzckwrzo7rs5da5aojtkb37awfcm6utjiapy (missing)
├── bafkreie2e4nhzliy2h7i3g7rlgf3fp5oaut3g33jeyrk2benzn3fetx6qa (missing)
├── bafkreidayonoigum6firpliwuraqmg2g5c5hfsaylxlqkdj2zhkshwgivu (missing)
├── bafkreidojh4opu5h3d2my3sjvpiykwgyy3cuhmmihqbg6rvcmbylpez6vm (missing)
├── bafkreifm5geczavpiwr5u6pbebcytea4i77vcbkss7ph4cad3fnsxn2n3m (missing)
├── bafkreieupt33dcwu5lqvhlmdeioitsmn4p4gysjpd2t6d6n67mzptrb6hy (missing)
├── bafkreih3fdqrv6u5amgcezvofj3zrmdzp2e45f3cewhbrwimcufpg5oefi (missing)
├── bafkreif6wucbg6j3nxa5nd6yxmhgil2wlsl7qg5uswmtos27iojzwkwn5a (missing)
├── bafkreigzjaf2kq7jh7yxzu52f4tfjbebeao6bniuxumt56vkk2xcawecmi (missing)
├── bafkreicmwax6dvhx2gcb4dkkb5ngfu2edo5q45h2wc4e3fwhhvxl5zcqwy (missing)
├── bafkreiefpufr6wmmen4avuddmcvmtf353fovq6oyw7fo2csndhn7ytwoya (missing)
├── bafkreidqcc5o6p3gmpb2gore2ivlsavccxs6breuimfgvydwseflgovqyu (missing)
└── bafkreignehckawkib4x4p3ldnpcor2xnijap24gcrzy3vxvgapz5m6dbya (missing)
```
