### ISSUE TITLE
Empty CAR on web3/nft.storage gateways

### ISSUE THREAD

**Issue by tennox** [web3-storage/freeway#94]
_[Posted on discord](https://discordapp.com/channels/806902334369824788/864892166470893588/1183533669219041300), redirected here_:

It seems to me the web3.storage gateways returns empty CAR files when requesting IPLD dagJson roots (uploaded via web3.storage)
https://api.web3.storage/car/baguqeerachr27553ixrmlk4kkipgrkwb2vu7noavzqhogfqrcrp7336cmspq
https://w3s.link/ipfs/baguqeerachr27553ixrmlk4kkipgrkwb2vu7noavzqhogfqrcrp7336cmspq/?format=car
https://w3s.link/ipfs/baguqeerachr27553ixrmlk4kkipgrkwb2vu7noavzqhogfqrcrp7336cmspq/?format=car&dag-scope=all
=> 60 bytes, empty CAR
(also nft.storage & w3s.link)

The cloudflare-ipfs/ipfs.io/4everland gateways work fine:
https://cloudflare-ipfs.com/ipfs/baguqeerachr27553ixrmlk4kkipgrkwb2vu7noavzqhogfqrcrp7336cmspq?format=car

Tried with many different DAG-JSON encoded examples of different sizes.

**Comment by alanshaw** [comment]
Possibly related to https://github.com/web3-storage/freeway/issues/86

**Comment by tennox** [comment]
It's the same no matter the DAG size though... and pretty annoying, we're falling back to cloudflare gateways, but they often take a while to discover stuff from nft.storage

**Comment by alanshaw** [comment]
This is because `ipfs-unixfs-exporter` does not have a dag-json resolver: https://github.com/ipfs/js-ipfs-unixfs/tree/master/packages/ipfs-unixfs-exporter/src/resolvers
